# Server Configuration
server.port=8080


# Custom Security Properties
app.encryption.key=${APP_ENCRYPTION_KEY}
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration-ms=86400000

# Meta Developer Credentials
app.facebook.client-id=${APP_FACEBOOK_CLIENT_ID}
app.facebook.client-secret=${APP_FACEBOOK_CLIENT_SECRET}
app.facebook.verify-token=${APP_FACEBOOK_VERIFY_TOKEN}

# Dummy Mail Configuration
spring.mail.host=localhost
spring.mail.port=2525

# Read .env file
spring.config.import=optional:file:.env[.properties]

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
